# Generated by Django 2.2.16 on 2022-07-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220730_1726'),
        ('reviews', '0007_auto_20220730_1714'),
    ]

    operations = [
    ]
