# Generated by Django 2.2.16 on 2022-07-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20220730_1742'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
