# Generated by Django 2.2.16 on 2022-08-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220731_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
